# Generated by Django 5.2.6 on 2025-09-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerkyc',
            name='land_records',
        ),
        migrations.RemoveField(
            model_name='sellerkyc',
            name='sale_deed',
        ),
        migrations.AddField(
            model_name='sellerkyc',
            name='additional_documents',
            field=models.ImageField(blank=True, help_text='Any additional supporting documents', upload_to='kyc/additional/'),
        ),
        migrations.AddField(
            model_name='sellerkyc',
            name='encumbrance_certificate',
            field=models.ImageField(blank=True, help_text='Upload Encumbrance Certificate (Required)', upload_to='kyc/encumbrance/'),
        ),
        migrations.AddField(
            model_name='sellerkyc',
            name='ownership_proof',
            field=models.ImageField(blank=True, help_text='Upload Ownership Proof Document (Required)', upload_to='kyc/ownership/'),
        ),
        migrations.AddField(
            model_name='sellerkyc',
            name='revenue_records',
            field=models.ImageField(blank=True, help_text='Upload Revenue Records (Required)', upload_to='kyc/revenue/'),
        ),
        migrations.AlterField(
            model_name='sellerkyc',
            name='aadhaar_card',
            field=models.ImageField(blank=True, help_text='Upload Aadhaar Card (Optional for additional verification)', upload_to='kyc/aadhaar/'),
        ),
        migrations.AlterField(
            model_name='sellerkyc',
            name='pan_card',
            field=models.ImageField(help_text='Upload PAN Card (Required)', upload_to='kyc/pan/'),
        ),
        migrations.AlterField(
            model_name='sellerkyc',
            name='tax_receipt',
            field=models.ImageField(blank=True, help_text='Upload Tax Receipt (Required)', upload_to='kyc/tax/'),
        ),
    ]
