# Generated by Django 5.2.6 on 2025-09-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_sellerkyc_land_records_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerkyc',
            name='aadhaar_card',
            field=models.ImageField(blank=True, help_text='Upload Aadhaar Card (Required)', upload_to='kyc/aadhaar/'),
        ),
    ]
