# Generated by Django 5.2.6 on 2025-09-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_sellerkyc_aadhaar_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerkyc',
            name='aadhaar_card',
            field=models.FileField(blank=True, help_text='Upload Aadhaar Card (Required) - Images or PDF', upload_to='kyc/aadhaar/'),
        ),
        migrations.AlterField(
            model_name='sellerkyc',
            name='additional_documents',
            field=models.FileField(blank=True, help_text='Any additional supporting documents - Images or PDF', upload_to='kyc/additional/'),
        ),
        migrations.AlterField(
            model_name='sellerkyc',
            name='encumbrance_certificate',
            field=models.FileField(blank=True, help_text='Upload Encumbrance Certificate (Required) - Images or PDF', upload_to='kyc/encumbrance/'),
        ),
        migrations.AlterField(
            model_name='sellerkyc',
            name='ownership_proof',
            field=models.FileField(blank=True, help_text='Upload Ownership Proof Document (Required) - Images or PDF', upload_to='kyc/ownership/'),
        ),
        migrations.AlterField(
            model_name='sellerkyc',
            name='pan_card',
            field=models.FileField(help_text='Upload PAN Card (Required) - Images or PDF', upload_to='kyc/pan/'),
        ),
        migrations.AlterField(
            model_name='sellerkyc',
            name='revenue_records',
            field=models.FileField(blank=True, help_text='Upload Revenue Records (Required) - Images or PDF', upload_to='kyc/revenue/'),
        ),
        migrations.AlterField(
            model_name='sellerkyc',
            name='tax_receipt',
            field=models.FileField(blank=True, help_text='Upload Tax Receipt (Required) - Images or PDF', upload_to='kyc/tax/'),
        ),
        migrations.AlterField(
            model_name='sellerkyc',
            name='voter_id',
            field=models.FileField(blank=True, help_text='Upload Voter ID (Optional) - Images or PDF', upload_to='kyc/voter/'),
        ),
    ]
